services:
  searxng:
    image: docker.io/searxng/searxng:latest
    environment:
      - SEARXNG_BASE_URL=https://search.mildlybrewed.com/
    restart: unless-stopped
    volumes:
      - ./searxng:/etc/searxng:rw
      - ./static/searxng.png:/usr/local/searxng/searx/static/themes/simple/img/searxng.png
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    healthcheck:
      test: "wget --no-verbose --spider --tries=1 http://127.0.0.1:8080 || exit 1"
      interval: 1m
      timeout: 5s
      retries: 3
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
